name: networking_app  # Change this to your project name
description: A new Flutter application

environment:
  sdk: ">=3.5.0 <4.0.0"  # Dart SDK constraint

dependencies:
  flutter:
    sdk: flutter
  chopper: ^4.0.3
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.3.0
  chopper_generator: ^4.0.0

flutter:
  uses-material-design: true
