import 'package:chopper/chopper.dart';

part 'chopper_service.chopper.dart';  // This file will be generated by build_runner

@ChopperApi()
abstract class PostService extends ChopperService {
  @Get(path: 'posts')
  Future<Response> getPosts();

  static PostService create() {
    final client = ChopperClient(
      baseUrl: 'https://jsonplaceholder.typicode.com',
      services: [_$PostService()],  // This method is generated by build_runner
      converter: JsonConverter(),
      interceptors: [
        (Request request) async {
          print('Chopper Request: ${request.method} ${request.url}');
          return request;
        },
        (Response response) {
          print('Chopper Response: ${response.statusCode} ${response.body}');
          return response;
        },
      ],
    );
    return _$PostService(client);  // This method is also generated by build_runner
  }
}
